Trust in motion (#2)
* minor changes to RolesReport

* plot params and plot components in RolesReport

* adds get_dataset_files

* changes signature of compute_role_change_intensity

* minor changes to nlp module

* cleans up commons

* moved skipgram to nlp

* adding fast sampling

* adds more plot types

* fixes rpgress bar thing

* charting embedding landscape

* fixes indexing bug

* adds t-SNE projection API

* implements the tracking_moving_activity API

* adds `build_diachronic_dataframe` API

* adds prefix filtering to diachronic df construction

* refactors build_diachronic df

* change plot summary default

* renames timeline to diachronic_df

* minor formatting

* fixes numpy.ndarray object has no attribute index

* Adds Skipgram model and its accelerator

* adds train and test function for DL model

* adds learn_dynamic_activity_model API

* adds some implementation notes for Tim

* enhance training report

* minor cleanup

* Adds Proscrustes Orthogonal transformation (and updates its plot)

* Plots embeddings aligned with Proscrustes Orthogonal

* fixes 'ImportError: cannot import name _check_input_dataframe'

* fixes recursive dependency issue btw nlp and data

* fixes another recursive dependency issue

* fixes 'dict' object has no attribute 'append' issue

* fixes union bug

* union issue (trying 1st fix)

* different types

* minor fixes in utils.data

* contributor not found fix

* another fix

* drop by condition

* adds missing parameter

* fixes get mode fn

* adds quiet console

* fixes describe timeline

* adds plot summary option

* removes device

* fixes train and test generator

* fixes issue with index

* tracks empty periods

* second try